### ISSUE TITLE
New Twitch Embed API

### ISSUE THREAD

**Issue by ShayBox** [Friss/TwitchStream#2]
Website is broken with Twitch's new API. i've got most of this fixed with my fork, but i cant get the viewers/followers to work

**Comment by Friss** [comment]
Yeah they stopped allowing un-authed requests so you need to pass a key with each request for the followers. 

I'll get a key just for this

**Comment by ShayBox** [comment]
Any news?

**Comment by ShayBox** [comment]
<3 thx

**Comment by Friss** [comment]
Thanks for the bump @ShayBox Changes should be live on master now.
